routes/web.php
<?php
Route::get('/',function(){
  return redirect()->route('login');
//   return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('penduduk', 'PendudukController');
	Route::resource('dusun', 'DusunController');
	Route::resource('kartukeluarga', 'KartuKeluargaController');
	Route::resource('detailkartukeluarga', 'DetailKartuKeluargaController');
	Route::resource('kematian', 'KematianController');
	Route::resource('kelahiran', 'KelahiranController');
	Route::resource('mutasi', 'MutasiController');
	Route::resource('surat', 'SuratController');
	Route::resource('user', 'UserController');

	Route::get('persetujuan/{id}/{fungsi}/{kondisi}', 'SupportController@persetujuan')->name('persetujuan');
	Route::get('file/{id}/{fungsi}', 'SupportController@file')->name('file');
});
//auth laravel
Auth::routes();

// Route::group(['prefix' => 'kematian'], function(){
// 	Route::get('persetujuan/{id}/{kondisi}', 'KematianController@persetujuan')->name('kematian.persetujuan');
// 	Route::get('file/{id}', 'KematianController@file')->name('kematian.file');
// });

app/Models/Penduduk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class Penduduk extends Model
{
    protected $table = 'penduduk';

    public function dusun()
    {
    	return $this->belongsTo('App\Models\Dusun');
    }

    public function mutasi()
    {
        return $this->hasOne('App\Models\Mutasi');
    }

    public function kartukeluarga()
    {
        return $this->hasOne('App\Models\KartuKeluarga', 'penduduk_id');
    }

    public function detailkartukeluarga()
    {
        return $this->hasOne('App\Models\DetailKartuKeluarga', 'penduduk_id');
    }

    public function kematian()
    {
        return $this->hasOne('App\Models\Kematian', 'penduduk_id');
    }

    public function kelahiran()
    {
        return $this->hasOne('App\Models\Kelahiran', 'penduduk_id');
    }

    public function scopeKepalaKeluarga($query)
    {
        return $query->where('kk_status', 1);
    }

    public function scopeBukanKepalaKeluarga($query)
    {
        return $query->where('kk_status', '<>', 1);
    }

    public function scopeTidakMuncul($query, $kematian, $pindah, $kk=null)
    {
        $query->whereNotIn('id', $kematian)->whereNotIn('id', $pindah);
        if($kk){
            $query->whereNotIn('id', $kk);
        }
        return $query;
    }

    public function getAnakKeberapaAttribute()
    {
        if($this->kelahiran){
            return $this->kelahiran->anak_ke;
        }
    }

    public function getTempatKelahiranAttribute()
    {
        if($this->kelahiran){
            return $this->kelahiran->tempat_lahir;
        }
    }

    public function getNamaDusunAttribute()
    {
    	if($this->dusun){
    		return $this->dusun->nama;
    	}
    }

    public function getAlamatTujuanAttribute()
    {
        if($this->mutasi){
            return $this->mutasi->alamat_pergi;
        }
    }

    public function getNamaAlamatAttribute()
    {
        if($this->dusun){
            return $this->dusun->alamat;
        }
    }

    public function getTanggalKematianAttribute()
    {
        if($this->kematian){
            return $this->kematian->tanggal;
        }
    }

    public function getTempatKematianAttribute()
    {
        if($this->kematian){
            return $this->kematian->tempat;
        }
    }

    public function getAlasanKematianAttribute()
    {
        if($this->kematian){
            return $this->kematian->alasan;
        }
    }

    public function getHariKematianAttribute()
    {
        if($this->kematian){
            $tanggal = Carbon::parse($this->kematian->tanggal);
            $tanggal = $tanggal->format('l');
            $tanggal = config('library.day.'.$tanggal);
            return $tanggal;
        }
    }

    public function getStatusKepalakeluargaAttribute()
    {
        return $this->kk_status == 1 ? 'Ya' : 'Tidak';
    }

    public function getNamaKepalaKeluargaAttribute()
    {
        if($this->kk_status == 1){
            return $this->nama;
        }else{
            if($this->detailkartukeluarga){
                return $this->detailkartukeluarga->nama_kepala_keluarga;
            }
        }
    }

    public function getNikKepalaKeluargaAttribute()
    {
        if($this->kk_status == 1){
            return $this->nik;
        }else{
            if($this->detailkartukeluarga){
                return $this->detailkartukeluarga->nik_kepala_keluarga;
            }
        }
    }

    public function getNomorKartuKeluargaAttribute()
    {
        if($this->kk_status == 1){
            if($this->kartukeluarga){
                return $this->kartukeluarga->nomor;
            }
        }else{
            if($this->detailkartukeluarga){
                return $this->detailkartukeluarga->nomor_kartu_keluarga;
            }
        }
    }

    public function getClassStatusKeadaanAttribute()
    {
        if($this->status_keadaan == 'kematian'){
            return 'bg-danger bg-lighten-4';
        }elseif($this->status_keadaan == 'pindah'){
            return 'bg-warning bg-lighten-4';
        }
    }
}

app/Http/Controllers/PendudukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Penduduk;
use App\Models\Dusun;

class PendudukController extends Controller
{
	public function __construct(Request $request, Penduduk $penduduk, Dusun $dusun)
	{
		$this->penduduk = $penduduk;
		$this->dusun 	= $dusun;
		$this->request 	= $request;
	}

    public function index()
    {
    	$penduduk 	= $this->penduduk->paginate(10);

    	return view('penduduk.index', compact('penduduk'));
    }

    public function create()
    {
    	return $this->form();
    }

    public function edit($id)
    {
    	return $this->form($id);
    }

    public function form($id = null){
        $cariPenduduk = $this->penduduk->find($id);

        if ($cariPenduduk) {
            session()->flashInput($cariPenduduk->toArray());
            $action = route('penduduk.update',$id) ;
            $method = 'PUT';
        }else{
            $action = route('penduduk.store');
            $method = 'POST';
        }

       $jenis_kelamin 	= config('library.jenis_kelamin');
       $agama 			= config('library.agama');
       $status 			= config('library.status');
       $kewarganegaraan = config('library.kewarganegaraan');
       $dusun 			= $this->dusun->get();

        return view('penduduk.form',compact(
        	'action', 'method', 'jenis_kelamin', 'agama', 
        	'status', 'kewarganegaraan', 'dusun'
        ));
    }

    public function store(){
        return $this->save();
    }

    public function update($id){
        return $this->save($id);
    }

    public function save($id = null){
        if ($id) {
            $penduduk = $this->penduduk->find($id);
        }else{
            $penduduk = $this->penduduk;
        }

        $input = $this->request->except('_token');
        // return $input;

        // $this->validate(request(),[
        //   'nik'  => 'required',
        //   'nama'  => 'required',
        // ]);

        $penduduk->nik  			= request('nik');
        $penduduk->nama  			= request('nama');
        $penduduk->tempat_lahir  	= request('tempat_lahir');
        $penduduk->tanggal_lahir  	= request('tanggal_lahir');
        $penduduk->jenis_kelamin  	= request('jenis_kelamin');
        $penduduk->dusun_id  		= request('dusun_id');
        $penduduk->rt  				= request('rt');
        $penduduk->rw  				= request('rw');
        $penduduk->kelurahan  		= request('kelurahan');
        $penduduk->kecamatan  		= request('kecamatan');
        $penduduk->agama  			= request('agama');
        $penduduk->status  			= request('status');
        $penduduk->pekerjaan  		= request('pekerjaan');
        $penduduk->kewarganegaraan  = request('kewarganegaraan');
        $penduduk->kk_status  		= request('kk_status') ? 1 : 0;
        $penduduk->save();

        return redirect()->route('penduduk.index');
    }

    public function destroy($id)
    {
    	$penduduk = $this->penduduk->find($id);
    	$penduduk->delete();

    	return redirect()->back();
    }
}

resources/views/penduduk/form.blade.php
@extends('_layouts.default')

@section('script-top')
<link rel="stylesheet" href="{{asset('robust/app-assets/css/plugins/forms/validation/form-validation.min.css')}}">
@endsection

@section('script-bottom')
<script src="{{asset('robust/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"> </script>
<script src="{{asset('robust/app-assets/js/scripts/forms/validation/form-validation.min.js')}}"> </script>
<script src="{{asset('js/backend.js')}}"> </script>
@endsection

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            <a href="{{ url('penduduk') }}" class="btn btn-secondary float-md-right mt-0">
            	<i class="icon-reply3"></i> Back
            </a>
        </div>
    </div>
</div>
<div class="content-body">
	<section class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<h4 class="card-title" id="basic-layout-square-controls">Form Penduduk</h4>
					<a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
					<div class="heading-elements">
						<ul class="list-inline mb-0">
							<li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="card-body collapse in">
					<div class="card-block">

						{{-- {!! Form::open(['class' => 'form form-horizontal', 'novalidate']) !!} --}}
						<form action="{{$action}}" method="post" class="form form-hotizontal">
							<input type="hidden" name="_method" value="{{$method}}">
          					{{ csrf_field() }}
							<div class="form-body pt-1">

								<div class="form-group row ">
									<label for="nik" class="col-md-2 label-control">NIK</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="nik" required value="{{ old('nik') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="nama" class="col-md-2 label-control">Nama</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="nama" required value="{{ old('nama') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="tempat_lahir" class="col-md-2 label-control">Tempat Lahir</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="tempat_lahir" required value="{{ old('tempat_lahir') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="tanggal_lahir" class="col-md-2 label-control">Tanggal Lahir</label>
									<div class="col-md-10">
										<input type="date" class="form-control" name="tanggal_lahir" required value="{{ old('tanggal_lahir') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="jenis_kelamin" class="col-md-2 label-control">Jenis Kelamin</label>
									<div class="col-md-10">
										<select class="form-control select2" id="jenis_kelamin" name="jenis_kelamin" required>
											<option value="">Pilih Jenis Kelamin</option>
											@foreach($jenis_kelamin as $item)
												<option value="{{$item}}" {{terpilih($item, 'jenis_kelamin')}}>{{$item}}</option>
											@endforeach
										</select>
										{{-- <div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div> --}}
										{{-- <div class="help-block font-small-3"></div> --}}
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="dusun_id" class="col-md-2 label-control">Nama Dusun</label>
									<div class="col-md-10">
										<select class="form-control items" name="dusun_id" required>
											<option value="">Pilih Nama Dusun</option>
											@foreach($dusun as $index => $item)
												<option value="{{$item->id}}" {{terpilih($item->id, 'dusun_id')}}>{{$item->nama}}</option>
											@endforeach
											{{-- <option value="1" {{terpilih(1, 'dusun_id')}}>bojo</option> --}}
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="rt" class="col-md-2 label-control">RT</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="rt" required value="{{ old('rt') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="rw" class="col-md-2 label-control">RW</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="rw" required value="{{ old('rw') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="kelurahan" class="col-md-2 label-control">keluarahan</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="kelurahan" required value="{{ old('kelurahan') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="kecamatan" class="col-md-2 label-control">kecamatan</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="kecamatan" required value="{{ old('kecamatan') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="agama" class="col-md-2 label-control">Agama</label>
									<div class="col-md-10">
										<select class="form-control items" name="agama" required>
											<option value="">Pilih Agama</option>
											@foreach($agama as $item)
												<option value="{{$item}}" {{terpilih($item, 'agama')}}>{{$item}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="status" class="col-md-2 label-control">Status</label>
									<div class="col-md-10">
										<select class="form-control items" name="status" required>
											<option value="">Pilih Status</option>
											@foreach($status as $item)
												<option value="{{$item}}" {{terpilih($item, 'status')}}>{{$item}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="pekerjaan" class="col-md-2 label-control">Pekerjaan</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="pekerjaan" required value="{{ old('pekerjaan') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="kewarganegaraan" class="col-md-2 label-control">Kewarganegaraan</label>
									<div class="col-md-10">
										<select class="form-control items" name="kewarganegaraan" required>
											<option value="">Pilih Kewarganegaraan</option>
											@foreach($kewarganegaraan as $item)
												<option value="{{$item}}" {{terpilih($item, 'kewarganegaraan')}}>{{$item}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label class="col-md-2 label-control">Kepala Keluarga</label>
									<div class="col-md-10">
										<fieldset class="checkboxsas">
						                {{-- <label> --}}
						                        <input type="checkbox" name="kk_status[]" value="1" {{old('kk_status') ? 'checked' : ''}}>
						      			{{-- </label> --}}
						            	</fieldset>
									</div>
								</div>

								<hr>

								<div class="offset-md-2">
									<button type="submit" class="btn btn-primary">
										<i class="icon-save"></i> Save
									</button>
								</div>
							</div>
						</form>
						{{-- {!! Form::close() !!} --}}

					</div>
				</div>
			</div>
		</div>
	</section>

</div>
@endsection

resources/views/penduduk/index.blade.php
@extends('_layouts.default')

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            @if(Auth::user()->role == 'pegawai')
            <a href="{{url('penduduk/create')}}" class="btn btn-primary float-md-right mt-0">
                <i class="icon-plus3"></i> Tambah
            </a>
            @endif
        </div>
    </div>
</div>
<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">Daftar Penduduk</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            {{-- <li><a data-action="collapse"><i class="icon-minus4"></i></a></li> --}}
                            {{-- <li><a data-action="expand"><i class="icon-expand2"></i></a></li> --}}
                        </ul>
                    </div>
                </div>
                {{-- <div class="card-body collapse in">
                    <div class="card-block pb-0">
                        <form method="get">
                            <div class="row">
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Total records : </label>
                                        <div class="form-control" readonly><strong>{{ number_format_short($total_record) }}</strong></div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Search by : </label>
                                        <select name="by" id="by" class="form-control">
                                            <option value="name" {{ (request('by') == 'name') ? 'selected' : '' }}>Nama</option>
                                            <option value="code" {{ (request('by') == 'code') ? 'selected' : '' }}>Nomor Barang</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Search box : </label>
                                        <div class="input-group">
                                            <input type="text" name="q" id="search" class="form-control" value="{{ request('q') }}" placeholder="Type here...">
                                            <span class="input-group-btn">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="icon-search"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div> --}}
                <!-- <div class="card-body"> -->
                <div class="card-block">
                    <div class="table-responsive bg-white">
                        <table class="table table-sm mb-0 table-bordered table-hover">
                            <thead class="bg-primary bg-lighten text-white">
                            <!-- <thead class="bg-lighten"> -->
                                <tr>
                                    <th width="20">No.</th>
                                    <th>NIK</th>
                                    <th>Nama</th>
                                    <th>Tempat Lahir</th>
                                    <th>Tanggal Lahir</th>
                                    <th>Jenis Kelamin</th>
                                    <th>Nama Dusun</th>
                                    <th>RT / RW</th>
                                    <th>Kelurahan</th>
                                    <th>Kecamatan</th>
                                    <th>Agama</th>
                                    <th>Status</th>
                                    <th>Kepala Keluarga</th>
                                    <th>Pekerjaan</th>
                                    <th>Kewarganegaraan</th>
                                    @if(Auth::user()->role == 'pegawai')
                                    <th width="" class="text-xs-center">Actions</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($penduduk as $index => $item)
                                    <tr class="{{$item->class_status_keadaan}}">
                                        <td>{{$index + 1}}</td>
                                        <td>{{$item->nik}}</td>
                                        <td>{{$item->nama}}</td>
                                        <td>{{$item->tempat_lahir}}</td>
                                        <td>{{$item->tanggal_lahir}}</td>
                                        <td>{{$item->jenis_kelamin}}</td>
                                        <td>{{$item->nama_dusun}}</td>
                                        <td>{{$item->rt}}/{{$item->rw}}</td>
                                        <td>{{$item->kelurahan}}</td>
                                        <td>{{$item->kecamatan}}</td>
                                        <td>{{$item->agama}}</td>
                                        <td>{{$item->status}}</td>
                                        <td>{{$item->status_kepalakeluarga}}</td>
                                        <td>{{$item->pekerjaan}}</td>
                                        <td>{{$item->kewarganegaraan}}</td>
                                        @if(Auth::user()->role == 'pegawai')
                                        <td class="text-xs-center">
                                            <a href="{{route('penduduk.edit',$item->id)}}" class="btn btn-sm btn-green">
                                                <i class="icon-pencil3"></i> edit
                                            </a>
                                            <a href="{{ route('penduduk.destroy',$item->id)}}"
                                                data-method="delete" data-confirm="Anda yakin akan menghapus data ini ?"
                                                class="btn btn-sm btn-danger" title="Hapus Data">
                                                <i class="icon-trash3"></i>
                                                Delete
                                            </a>
                                        </td>
                                        @endif
                                    </tr>
                                @empty
                                    <tr class="bg-info bg-lighten-4">
                                        <td colspan="16">
                                            <strong class="text-info"><center>Data Kosong</center></strong>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- </div> -->
            </div>

            <div class="card-block pr-0">
                <nav aria-label="Page navigation" class="text-xs-right">
                    {!! $penduduk->links() !!}
                </nav>
            </div>
        </div>
    </div>
</div>
@endsection