routes/web.php
<?php
Route::get('/',function(){
  return redirect()->route('login');
//   return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('penduduk', 'PendudukController');
	Route::resource('dusun', 'DusunController');
	Route::resource('kartukeluarga', 'KartuKeluargaController');
	Route::resource('detailkartukeluarga', 'DetailKartuKeluargaController');
	Route::resource('kematian', 'KematianController');
	Route::resource('kelahiran', 'KelahiranController');
	Route::resource('mutasi', 'MutasiController');
	Route::resource('surat', 'SuratController');
	Route::resource('user', 'UserController');

	Route::get('persetujuan/{id}/{fungsi}/{kondisi}', 'SupportController@persetujuan')->name('persetujuan');
	Route::get('file/{id}/{fungsi}', 'SupportController@file')->name('file');
});
//auth laravel
Auth::routes();

// Route::group(['prefix' => 'kematian'], function(){
// 	Route::get('persetujuan/{id}/{kondisi}', 'KematianController@persetujuan')->name('kematian.persetujuan');
// 	Route::get('file/{id}', 'KematianController@file')->name('kematian.file');
// });

app/Models/Mutasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mutasi extends Model
{
    protected $table = 'mutasi';

    public function penduduk()
    {
    	return $this->belongsTo('App\Models\Penduduk');
    }

    public function scopePindah($query)
    {
        return $query->where('status_mutasi', 'pindah');
    }

    public function scopeDatang($query)
    {
        return $query->where('status_mutasi', 'datang');
    }

    public function scopeKecualiPendudukid($query, $id)
    {
        return $query->where('penduduk_id', '<>', $id);
    }

	public function getNamaPendudukAttribute()
    {
    	if($this->penduduk){
    		return $this->penduduk->nama;
    	}
    }

    public function getClassStatusMutasiAttribute()
    {
        if($this->status_mutasi == 'pindah'){
            return 'bg-danger bg-lighten-4';
        }
    }

    public function getAlasanPersetujuanAttribute()
    {
        if($this->status_mutasi == 'pindah'){
            if($this->persetujuan == 1){
                return 'Disetujui';
            }elseif($this->persetujuan == 2){
                return 'Tidak disetujui';
            }else{
                return 'Belum ada persetujuan';
            }
        }
    }
}

app/Http/Controllers/MutasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Penduduk;
use App\Models\Mutasi;
use App\Models\Kematian;
use App\Models\File;

use App\Supports\FileManager;

class MutasiController extends Controller
{
	public function __construct(
								Request $request, 
								Penduduk $penduduk,
								Mutasi $mutasi,
                                File $file,
                                Kematian $kematian,
                                FileManager $filemanager
							)
	{
		$this->penduduk 	= $penduduk;
		$this->mutasi 		= $mutasi;
        $this->file         = $file;
		$this->request 		= $request;
        $this->kematian     = $kematian;
        $this->filemanager  = $filemanager;
	}

    public function index()
    {
    	$mutasi = $this->mutasi;
        $file          = []; 

        foreach($mutasi->get() as $index => $item){
            $file[$item->id] =  $this->file->kondisi($item->penduduk_id, 'mutasi')->pluck('nama');
        }

        $mutasi = $mutasi->paginate(10);

    	return view('mutasi.index', compact('mutasi', 'file'));
    }

    public function create()
    {
    	return $this->form();
    }

    public function edit($id)
    {
    	return $this->form($id);
    }

    public function form($id = null){
        $carimutasi = $this->mutasi->find($id);

        if ($carimutasi) {
            session()->flashInput($carimutasi->toArray());
            $action = route('mutasi.update',$id);
            $method = 'PUT';

            $penduduk_id = $carimutasi->penduduk_id;
        }else{
            $action = route('mutasi.store');
            $method = 'POST';

            $penduduk_id = '';
        }

       	$kematian       = $this->kematian->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $pindah         = $this->mutasi->pindah()->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $penduduk       = $this->penduduk->tidakMuncul($kematian, $pindah)->get();
        $file           = $this->file->kondisi($penduduk_id, 'mutasi')->get();
       	$status_mutasi	= config('library.status_mutasi');

        return view('mutasi.form',compact(
        	'action', 'method', 'penduduk', 'status_mutasi', 'file'
        ));
    }

    public function store(){
        return $this->save();
    }

    public function update($id){
        return $this->save($id);
    }

    public function save($id = null){
        if ($id) {
            $mutasi = $this->mutasi->find($id);
        }else{
            $mutasi = $this->mutasi;
        }

        $input = $this->request->except('_token');
        // return $input;

        // upload file ke table file //
        $this->filemanager->uploadFile(
            request()->file('file'), 
            request('penduduk_id'), 
            'mutasi'
        );

        $mutasi->penduduk_id	= request('penduduk_id');
        $mutasi->alamat_datang	= request('alamat_datang');
        $mutasi->alamat_pergi	= request('alamat_pergi');
        $mutasi->status_mutasi	= request('status_mutasi');
        $mutasi->alasan			= request('alasan');
        $mutasi->save();

        if(request('status_mutasi') == 'pindah'){
            $penduduk = $this->penduduk->find(request('penduduk_id'));
            $penduduk->status_keadaan = 'pindah';
            $penduduk->save();
        }

        return redirect()->route('mutasi.index');
    }

    public function destroy($id)
    {
    	$mutasi = $this->mutasi->find($id);

        $penduduk = $this->penduduk->find($mutasi->penduduk_id);
        $penduduk->status_keadaan = '';
        $file      = $this->file->where('penduduk_id', $mutasi->penduduk_id);

        $file->delete();
        $penduduk->save();
    	$mutasi->delete();

    	return redirect()->back();
    }
}

resources/views/mutasi/form.blade.php
@extends('_layouts.default')

@section('script-top')
<link rel="stylesheet" href="{{asset('robust/app-assets/css/plugins/forms/validation/form-validation.min.css')}}">
@endsection

@section('script-bottom')
<script src="{{asset('robust/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"> </script>
<script src="{{asset('robust/app-assets/js/scripts/forms/validation/form-validation.min.js')}}"> </script>
<script src="{{asset('js/backend.js')}}"> </script>
@endsection

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            <a href="{{ url('mutasi') }}" class="btn btn-secondary float-md-right mt-0">
            	<i class="icon-reply3"></i> Back
            </a>
        </div>
    </div>
</div>
<div class="content-body">
	<section class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<h4 class="card-title" id="basic-layout-square-controls">Form Mutasi</h4>
					<a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
					<div class="heading-elements">
						<ul class="list-inline mb-0">
							<li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="card-body collapse in">
					<div class="card-block">

						{{-- {!! Form::open(['class' => 'form form-horizontal', 'novalidate']) !!} --}}
						<form action="{{$action}}" method="post" class="form form-hotizontal" enctype="multipart/form-data">
							<input type="hidden" name="_method" value="{{$method}}">
          					{{ csrf_field() }}
							<div class="form-body pt-1">

								<div class="form-group row position-relative">
									<label for="penduduk_id" class="col-md-2 label-control">NIK Penduduk</label>
									<div class="col-md-10">
										<select class="form-control select2" name="penduduk_id" required>
											<option value="">Pilih NIK Penduduk</option>
											@foreach($penduduk as $index => $item)
												<option value="{{$item->id}}" {{terpilih($item->id, 'penduduk_id')}}>{{$item->nik}} / {{$item->nama}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="alamat_datang" class="col-md-2 label-control">Alamat Sebelum</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="alamat_datang" required value="{{ old('alamat_datang') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="alamat_pergi" class="col-md-2 label-control">Alamat tujuan</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="alamat_pergi" required value="{{ old('alamat_pergi') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="status_mutasi" class="col-md-2 label-control">Status Mutasi</label>
									<div class="col-md-10">
										<select class="form-control items" name="status_mutasi" required>
											<option value="">Pilih Status Mutasi</option>
											@foreach($status_mutasi as $item)
												<option value="{{$item}}" {{terpilih($item, 'status_mutasi')}}>{{$item}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="alasan" class="col-md-2 label-control">Alasan</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="alasan" required value="{{ old('alasan') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								@if(!$file->isEmpty())
									<div class="form-group row ">
										<label for="file" class="col-md-2 label-control">Unduh Berkas</label>
										<div class="col-md-10">
											@foreach($file as $index => $item)
												<a href="{{asset('storages')}}/{{$item->nama}}" class="btn btn-md btn-success">Lampiran {{$index + 1}}</a>
											@endforeach
										</div>
									</div>
								@else
									<div class="form-group row ">
										<label for="file" class="col-md-2 label-control">Masukkan Berkas Pendukung</label>
										<div class="col-md-10">
											<input type="file" class="form-control" name="file[]" multiple="multiple" required>
											<div class="help-block font-small-3">
												
											</div>
										</div>
									</div>
								@endif

								<hr>

								<div class="offset-md-2">
									<button type="submit" class="btn btn-primary">
										<i class="icon-save"></i> Save
									</button>
								</div>
							</div>
						</form>
						{{-- {!! Form::close() !!} --}}

					</div>
				</div>
			</div>
		</div>
	</section>

</div>
@endsection

resources/views/mutasi/index.blade.php
@extends('_layouts.default')

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            @if(Auth::user()->role == 'pegawai')
            <a href="{{url('mutasi/create')}}" class="btn btn-primary float-md-right mt-0">
                <i class="icon-plus3"></i> Tambah
            </a>
            @endif
        </div>
    </div>
</div>
<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">Daftar Mutasi</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            {{-- <li><a data-action="collapse"><i class="icon-minus4"></i></a></li> --}}
                            {{-- <li><a data-action="expand"><i class="icon-expand2"></i></a></li> --}}
                        </ul>
                    </div>
                </div>
                {{-- <div class="card-body collapse in">
                    <div class="card-block pb-0">
                        
                    </div>
                </div> --}}
                <!-- <div class="card-body"> -->
                <div class="card-block">
                    <div class="table-responsive bg-white">
                        <table class="table table-sm mb-0 table-bordered table-hover">
                            <thead class="bg-primary bg-lighten text-white">
                            <!-- <thead class="bg-lighten"> -->
                                <tr>
                                    <th>No.</th>
                                    <th>Nama Penduduk</th>
                                    <th>Alamat Sebelum</th>
                                    <th>Alamat Tujuan</th>
                                    <th>status Mutasi</th>
                                    <th>Alasan</th>
                                    <th>Persetujuan</th>
                                    @if(Auth::user()->role == 'kepala')
                                    <th>Lampiran</th>
                                    @endif
                                    {{-- @if(Auth::user()->permission_actions) --}}
                                    <th width="180" class="text-xs-center">Actions</th>
                                    {{-- @endif --}}
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($mutasi as $index => $item)
                                    <tr class="{{$item->class_status_mutasi}}">
                                        <td>{{$index + 1}}</td>
                                        <td>{{$item->nama_penduduk}}</td>
                                        <td>{{$item->alamat_datang}}</td>
                                        <td>{{$item->alamat_pergi}}</td>
                                        <td>{{$item->status_mutasi}}</td>
                                        <td>{{$item->alasan}}</td>
                                        <td>{{$item->alasan_persetujuan}}</td>
                                        @if(Auth::user()->role == 'kepala')
                                        <td class="valign-middle">
                                            @foreach($file[$item->id] as $index => $value)
                                            <a href="{{asset('storages')}}/{{$value}}" class="btn btn-sm btn-success">Lampiran {{$index + 1}}</a>
                                            @endforeach
                                        </td>
                                        @endif
                                        <td class="text-xs-center">
                                             @if(Auth::user()->role == 'pegawai')
                                                @if($item->status_mutasi == 'pindah')
                                                    <a href="{{route('file', [$item->penduduk_id, 'mutasi'])}}" class="btn btn-sm btn-info {{tombol_berkas($item->persetujuan)}}">
                                                        <i class="icon-file2"></i> Unduh Surat
                                                    </a>
                                                @endif
                                            @else
                                                @if($item->status_mutasi == 'pindah')
                                                    <a href="{{route('persetujuan',[$item->id, 'mutasi', 'setuju'])}}" class="btn btn-sm btn-info">
                                                        <i class="icon-check2"></i> Setujui
                                                    </a>
                                                    <a href="{{route('persetujuan', [$item->id, 'mutasi', 'tidak'])}}" class="btn btn-sm btn-danger">
                                                         <i class="icon-cross2"></i> Tidak Setujui
                                                    </a>
                                                @endif
                                            @endif
                                            @if(Auth::user()->role == 'pegawai')
                                            <a href="{{route('mutasi.edit',$item->id)}}" class="btn btn-sm btn-green">
                                                <i class="icon-pencil3"></i> Edit
                                            </a>
                                            <a href="{{ route('mutasi.destroy',$item->id)}}"
                                                data-method="delete" data-confirm="Anda yakin akan menghapus data ini ?"
                                                class="btn btn-sm btn-danger" title="Hapus Data">
                                                <i class="icon-trash3"></i>
                                                Delete
                                            </a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr class="bg-info bg-lighten-4">
                                        <td colspan="8">
                                            <strong class="text-info"><center>Data Kosong</center></strong>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- </div> -->
            </div>

            <div class="card-block pr-0">
                <nav aria-label="Page navigation" class="text-xs-right">
                    {!! $mutasi->links() !!}
                </nav>
            </div>
        </div>
    </div>
</div>
@endsection