routes/web.php
<?php
Route::get('/',function(){
  return redirect()->route('login');
//   return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('penduduk', 'PendudukController');
	Route::resource('dusun', 'DusunController');
	Route::resource('kartukeluarga', 'KartuKeluargaController');
	Route::resource('detailkartukeluarga', 'DetailKartuKeluargaController');
	Route::resource('kematian', 'KematianController');
	Route::resource('kelahiran', 'KelahiranController');
	Route::resource('mutasi', 'MutasiController');
	Route::resource('surat', 'SuratController');
	Route::resource('user', 'UserController');

	Route::get('persetujuan/{id}/{fungsi}/{kondisi}', 'SupportController@persetujuan')->name('persetujuan');
	Route::get('file/{id}/{fungsi}', 'SupportController@file')->name('file');
});
//auth laravel
Auth::routes();

// Route::group(['prefix' => 'kematian'], function(){
// 	Route::get('persetujuan/{id}/{kondisi}', 'KematianController@persetujuan')->name('kematian.persetujuan');
// 	Route::get('file/{id}', 'KematianController@file')->name('kematian.file');
// });

app/Models/Kelahiran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kelahiran extends Model
{
    protected $table = 'kelahiran';

    public function penduduk()
    {
    	return $this->belongsTo('App\Models\Penduduk');
    }

    public function scopeKecualiPendudukid($query, $id)
    {
        return $query->where('penduduk_id', '<>', $id);
    }

	public function getNamaPendudukAttribute()
    {
    	if($this->penduduk){
    		return $this->penduduk->nama;
    	}
    }

    public function getAlamatPendudukAttribute()
    {
    	if($this->penduduk){
    		return $this->penduduk->dusun->nama;
    	}
    }

    public function getAlasanPersetujuanAttribute()
    {
        if($this->persetujuan == 1){
            return 'Disetujui';
        }elseif($this->persetujuan == 2){
            return 'Tidak disetujui';
        }else{
            return 'Belum ada persetujuan';
        }
    }
}

app/Http/Controllers/KelahiranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Kelahiran;
use App\Models\Penduduk;
use App\Models\Kematian;
use App\Models\Mutasi;
use App\Models\File;

use App\Supports\FileManager;

class KelahiranController extends Controller
{
	public function __construct(
								Request $request, 
								Penduduk $penduduk,
								Kelahiran $kelahiran,
                                FileManager $filemanager,
                                Kematian $kematian,
                                File $file,
                                Mutasi $mutasi
							)
	{
		$this->penduduk 		= $penduduk;
		$this->kelahiran 		= $kelahiran;
		$this->request 			= $request;
        $this->mutasi           = $mutasi;
        $this->file             = $file;
        $this->kematian         = $kematian;
        $this->filemanager      = $filemanager;
	}

    public function index()
    {
    	$kelahiran     = $this->kelahiran;
        $file          = []; 

        foreach($kelahiran->get() as $index => $item){
            $file[$item->id] =  $this->file->kondisi($item->penduduk_id, 'kelahiran')->pluck('nama');
        }

        $kelahiran = $kelahiran->paginate(10);

    	return view('kelahiran.index', compact('kelahiran', 'file'));
    }

    public function create()
    {
    	return $this->form();
    }

    public function edit($id)
    {
    	return $this->form($id);
    }

    public function form($id = null){
        $carikelahiran = $this->kelahiran->find($id);

        if ($carikelahiran) {
            session()->flashInput($carikelahiran->toArray());
            $action = route('kelahiran.update',$id);
            $method = 'PUT';

            $penduduk_id = $carikelahiran->penduduk_id;
        }else{
            $action = route('kelahiran.store');
            $method = 'POST';

            $penduduk_id = '';
        }

        $kematian       = $this->kematian->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $kelahiran      = $this->kelahiran->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $pindah         = $this->mutasi->pindah()->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
       	$penduduk 		= $this->penduduk->tidakMuncul($kematian, $pindah, $kelahiran)->get();
        $file           = $this->file->kondisi($penduduk_id, 'kelahiran')->get();
       	$jenis_kelamin	= config('library.jenis_kelamin');

        return view('kelahiran.form',compact(
        	'action', 'method', 'penduduk', 'jenis_kelamin', 'file'
        ));
    }

    public function store(){
        return $this->save();
    }

    public function update($id){
        return $this->save($id);
    }

    public function save($id = null){
        if ($id) {
            $kelahiran = $this->kelahiran->find($id);
        }else{
            $kelahiran = $this->kelahiran;
        }

        $input = $this->request->except('_token');
        // return $input;

        // $this->validate($this->request,[
        //   'file'  => 'size:2000'
        // ]);

        // upload file ke table file //
        $this->filemanager->uploadFile(
            request()->file('file'), 
            request('penduduk_id'), 
            'kelahiran'
        );

        $kelahiran->penduduk_id		= request('penduduk_id');
        $kelahiran->tempat          = request('tempat');
        $kelahiran->anak_ke			= request('anak_ke');
        $kelahiran->tanggal			= request('tanggal');
        $kelahiran->jenis_kelamin	= request('jenis_kelamin');
        $kelahiran->save();

        return redirect()->route('kelahiran.index');
    }

    public function destroy($id)
    {
    	$kelahiran = $this->kelahiran->find($id);
        $file      = $this->file->where('penduduk_id', $kelahiran->penduduk_id);

        $file->delete();
    	$kelahiran->delete();



    	return redirect()->back();
    }
}

resources/views/kelahiran/form.blade.php
@extends('_layouts.default')

@section('script-top')
<link rel="stylesheet" href="{{asset('robust/app-assets/css/plugins/forms/validation/form-validation.min.css')}}">
@endsection

@section('script-bottom')
<script src="{{asset('robust/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"> </script>
<script src="{{asset('robust/app-assets/js/scripts/forms/validation/form-validation.min.js')}}"> </script>
<script src="{{asset('js/backend.js')}}"> </script>
@endsection

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            <a href="{{ url('kelahiran') }}" class="btn btn-secondary float-md-right mt-0">
            	<i class="icon-reply3"></i> Back
            </a>
        </div>
    </div>
</div>
<div class="content-body">
	<section class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<h4 class="card-title" id="basic-layout-square-controls">Form Kelahiran</h4>
					<a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
					<div class="heading-elements">
						<ul class="list-inline mb-0">
							<li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="card-body collapse in">
					<div class="card-block">

						{{-- {!! Form::open(['class' => 'form form-horizontal', 'novalidate']) !!} --}}
						<form action="{{$action}}" method="post" class="form form-hotizontal" enctype="multipart/form-data">
							<input type="hidden" name="_method" value="{{$method}}">
          					{{ csrf_field() }}
							<div class="form-body pt-1">

								<div class="form-group row position-relative">
									<label for="penduduk_id" class="col-md-2 label-control">NIK Penduduk</label>
									<div class="col-md-10">
										<select class="form-control select2" name="penduduk_id" required>
											<option value="">Pilih NIK Penduduk</option>
											@foreach($penduduk as $index => $item)
												<option value="{{$item->id}}" {{terpilih($item->id, 'penduduk_id')}}>{{$item->nik}} / {{$item->nama}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="tempat" class="col-md-2 label-control">Tempat Kelahiran</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="tempat" required value="{{ old('tempat') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="anak_ke" class="col-md-2 label-control">Anak Ke-</label>
									<div class="col-md-10">
										<input type="text" class="form-control" name="anak_ke" required value="{{ old('anak_ke') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row ">
									<label for="tanggal" class="col-md-2 label-control">Tanggal Kelahiran</label>
									<div class="col-md-10">
										<input type="date" class="form-control" name="tanggal" required value="{{ old('tanggal') }}">
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="jenis_kelamin" class="col-md-2 label-control">Jenis Kelamin</label>
									<div class="col-md-10">
										<select class="form-control" name="jenis_kelamin" required>
											<option value="">Pilih Jenis Kelamin</option>
											@foreach($jenis_kelamin as $item)
												<option value="{{$item}}" {{terpilih($item, 'jenis_kelamin')}}>{{$item}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								@if(!$file->isEmpty())
									<div class="form-group row ">
										<label for="file" class="col-md-2 label-control">Unduh Berkas</label>
										<div class="col-md-10">
											@foreach($file as $index => $item)
												<a href="{{asset('storages')}}/{{$item->nama}}" class="btn btn-md btn-success">Lampiran {{$index + 1}}</a>
											@endforeach
										</div>
									</div>
								@else
									<div class="form-group row ">
										<label for="file" class="col-md-2 label-control">Masukkan Berkas Pendukung</label>
										<div class="col-md-10">
											<input type="file" class="form-control" name="file[]" multiple="multiple" required>
											<div class="help-block font-small-3">
												
											</div>
										</div>
									</div>
								@endif

								<hr>

								<div class="offset-md-2">
									<button type="submit" class="btn btn-primary">
										<i class="icon-save"></i> Save
									</button>
								</div>
							</div>
						{{-- {!! Form::close() !!} --}}

					</div>
				</div>
			</div>
		</div>
	</section>

</div>
@endsection

resources/views/kelahiran/index.blade.php
@extends('_layouts.default')

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            @if(Auth::user()->role == 'pegawai')
            <a href="{{url('kelahiran/create')}}" class="btn btn-primary float-md-right mt-0">
                <i class="icon-plus3"></i> Tambah
            </a>
            @endif
        </div>
    </div>
</div>
<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">Daftar Kelahiran</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            {{-- <li><a data-action="collapse"><i class="icon-minus4"></i></a></li> --}}
                            {{-- <li><a data-action="expand"><i class="icon-expand2"></i></a></li> --}}
                        </ul>
                    </div>
                </div>
                {{-- <div class="card-body collapse in">
                    <div class="card-block pb-0">
                        <form method="get">
                            <div class="row">
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Total records : </label>
                                        <div class="form-control" readonly><strong>{{ number_format_short($total_record) }}</strong></div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Search by : </label>
                                        <select name="by" id="by" class="form-control">
                                            <option value="name" {{ (request('by') == 'name') ? 'selected' : '' }}>Nama</option>
                                            <option value="code" {{ (request('by') == 'code') ? 'selected' : '' }}>Nomor Barang</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Search box : </label>
                                        <div class="input-group">
                                            <input type="text" name="q" id="search" class="form-control" value="{{ request('q') }}" placeholder="Type here...">
                                            <span class="input-group-btn">
                                                <button type="submit" class="btn btn-primary">
                            <i class="icon-cross2"></i>                        <i class="icon-search"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div> --}}
                <!-- <div class="card-body"> -->
                <div class="card-block">
                    <div class="table-responsive bg-white">
                        <table class="table table-sm mb-0 table-bordered table-hover">
                            <thead class="bg-primary bg-lighten text-white">
                            <!-- <thead class="bg-lighten"> -->
                                <tr>
                                    <th width="10">No.</th>
                                    <th>Nama Penduduk</th>
                                    <th>Nama Dusun Penduduk</th>
                                    <th>Tempat Kelahiran</th>
                                    <th>Tanggal Kelahiran</th>
                                    <th>Jenis Kelamin</th>
                                    <th>Persetujuan</th>
                                    @if(Auth::user()->role == 'kepala')
                                    <th>Lampiran</th>
                                    @endif
                                    {{-- @if(Auth::user()->permission_actions) --}}
                                    <th width="180" class="text-xs-center">Actions</th>
                                    {{-- @endif --}}
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($kelahiran as $index => $item)
                                    <tr>
                                        <td>{{$index + 1}}</td>
                                        <td>{{$item->nama_penduduk}}</td>
                                        <td>{{$item->alamat_penduduk}}</td>
                                        <td>{{$item->tempat}}</td>
                                        <td>{{$item->tanggal}}</td>
                                        <td>{{$item->jenis_kelamin}}</td>
                                        <td>{{$item->alasan_persetujuan}}</td>
                                        @if(Auth::user()->role == 'kepala')
                                        <td class="valign-middle">
                                            @foreach($file[$item->id] as $index => $value)
                                            <a href="{{asset('storages')}}/{{$value}}" class="btn btn-sm btn-success">Lampiran {{$index + 1}}</a>
                                            @endforeach
                                        </td>
                                        @endif
                                        <td class="text-xs-center">
                                            @if(Auth::user()->role == 'pegawai')
                                                <a href="{{route('file', [$item->penduduk_id, 'kelahiran'])}}" class="btn btn-sm btn-info {{tombol_berkas($item->persetujuan)}}">
                                                    <i class="icon-file2"></i> Unduh Surat
                                                </a>
                                            @else
                                                 <a href="{{route('persetujuan',[$item->id, 'kelahiran', 'setuju'])}}" class="btn btn-sm btn-info">
                                                    <i class="icon-check2"></i> Setujui
                                                </a>
                                                <a href="{{route('persetujuan', [$item->id, 'kelahiran', 'tidak'])}}" class="btn btn-sm btn-danger">
                                                    <i class="icon-cross2"></i> Tidak Setujui
                                                </a>
                                            @endif
                                            @if(Auth::user()->role == 'pegawai')
                                            <a href="{{route('kelahiran.edit',$item->id)}}" class="btn btn-sm btn-green">
                                                <i class="icon-pencil3"></i> Edit
                                            </a>
                                            <a href="{{ route('kelahiran.destroy',$item->id)}}"
                                                data-method="delete" data-confirm="Anda yakin akan menghapus data ini ?"
                                                class="btn btn-sm btn-danger" title="Hapus Data">
                                                <i class="icon-trash3"></i>
                                                Delete
                                            </a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr class="bg-info bg-lighten-4">
                                        <td colspan="9">
                                            <strong class="text-info"><center>Data Kosong</center></strong>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- </div> -->
            </div>

            <div class="card-block pr-0">
                <nav aria-label="Page navigation" class="text-xs-right">
                    {!! $kelahiran->links() !!}
                </nav>
            </div>
        </div>
    </div>
</div>
@endsection