routes/web.php
<?php
Route::get('/',function(){
  return redirect()->route('login');
//   return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('penduduk', 'PendudukController');
	Route::resource('dusun', 'DusunController');
	Route::resource('kartukeluarga', 'KartuKeluargaController');
	Route::resource('detailkartukeluarga', 'DetailKartuKeluargaController');
	Route::resource('kematian', 'KematianController');
	Route::resource('kelahiran', 'KelahiranController');
	Route::resource('mutasi', 'MutasiController');
	Route::resource('surat', 'SuratController');
	Route::resource('user', 'UserController');

	Route::get('persetujuan/{id}/{fungsi}/{kondisi}', 'SupportController@persetujuan')->name('persetujuan');
	Route::get('file/{id}/{fungsi}', 'SupportController@file')->name('file');
});
//auth laravel
Auth::routes();

// Route::group(['prefix' => 'kematian'], function(){
// 	Route::get('persetujuan/{id}/{kondisi}', 'KematianController@persetujuan')->name('kematian.persetujuan');
// 	Route::get('file/{id}', 'KematianController@file')->name('kematian.file');
// });

app/Models/DetailKartuKeluarga.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DetailKartuKeluarga extends Model
{
    protected $table = 'detail_kartu_keluarga';

    public function kartukeluarga()
    {
    	return $this->belongsTo('App\Models\KartuKeluarga', 'kartukeluarga_id');
    }

    public function penduduk()
    {
    	return $this->belongsTo('App\Models\Penduduk');
    }

    public function scopeKecualiPendudukid($query, $id)
    {
        return $query->where('penduduk_id', '<>', $id);
    }

    public function getNamaPendudukAttribute()
    {
    	if($this->penduduk){
    		return $this->penduduk->nama;
    	}
    }

    public function getNikPendudukAttribute()
    {
        if($this->penduduk){
            return $this->penduduk->nik;
        }
    }

    public function getNomorKartuKeluargaAttribute()
    {
        if($this->kartukeluarga){
            return $this->kartukeluarga->nomor;
        }
    }

    public function getNamaKepalaKeluargaAttribute()
    {
        if($this->kartukeluarga){
            return $this->kartukeluarga->penduduk->nama;
        }
    }

    public function getNikKepalaKeluargaAttribute()
    {
        if($this->kartukeluarga){
            return $this->kartukeluarga->penduduk->nik;
        }
    }
}

app/Http/Controllers/DetailKartuKeluargaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\KartuKeluarga;
use App\Models\Penduduk;
use App\Models\Mutasi;
use App\Models\Kematian;
use App\Models\DetailKartuKeluarga;

class DetailKartuKeluargaController extends Controller
{
    public function __construct(
                                Request $request, 
                                DetailKartuKeluarga $detailkartukeluarga, 
                                KartuKeluarga $kartukeluarga, 
                                Mutasi $mutasi,
                                Kematian $kematian,
                                Penduduk $penduduk
                            )
	{
        $this->kartukeluarga        = $kartukeluarga;
		$this->penduduk 		    = $penduduk;
        $this->mutasi               = $mutasi;
        $this->kematian             = $kematian;
		$this->detailkartukeluarga 	= $detailkartukeluarga;
		$this->request 				= $request;

        $carikartukeluarga = $this->kartukeluarga->find(request('kk'));

        view()->share([
            'carikartukeluarga'     => $carikartukeluarga,
        ]);
	}

    public function index()
    {
    	$detailkartukeluarga = $this->detailkartukeluarga->where('kartukeluarga_id', request('kk'))->paginate(10);

        // return $kartukeluarga->toSql();

    	return view('detailkartukeluarga.index', compact('detailkartukeluarga'));
    }

    public function create()
    {
        return $this->form();
    }

    public function edit($id)
    {
        return $this->form($id);
    }

    public function form($id = null){
        $caridetailkartukeluarga = $this->detailkartukeluarga->find($id);

        if ($caridetailkartukeluarga) {
            session()->flashInput($caridetailkartukeluarga->toArray());
            $action = route('detailkartukeluarga.update', $id);
            $method = 'PUT';

            $penduduk_id = $caridetailkartukeluarga->penduduk_id;
        }else{
            $action = route('detailkartukeluarga.store');
            $method = 'POST';
            
            $penduduk_id = '';
        }

        $kematian   = $this->kematian->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $pindah     = $this->mutasi->pindah()->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $kk         = $this->detailkartukeluarga->kecualiPendudukid($penduduk_id)->pluck('penduduk_id');
        $penduduk   = $this->penduduk->bukanKepalaKeluarga()->tidakMuncul($kematian, $pindah, $kk)->get();

        return view('detailkartukeluarga.form',compact(
            'action', 'method', 'penduduk'
        ));
    }

    public function store(){
        return $this->save();
    }

    public function update($id){
        return $this->save($id);
    }

    public function save($id = null){
        if ($id) {
            $detailkartukeluarga = $this->detailkartukeluarga->find($id);
        }else{
            $detailkartukeluarga = $this->detailkartukeluarga;
        }

        // $input = $this->request->except('_token');
        // return $input;

        // $this->validate(request(),[
        //   'nik'  => 'required',
        //   'nama'  => 'required',
        // ]);

        $detailkartukeluarga->penduduk_id       = request('penduduk_id');
        $detailkartukeluarga->role              = request('role');
        $detailkartukeluarga->kartukeluarga_id  = request('kartukeluarga_id');
        $detailkartukeluarga->save();

        return redirect()->route('detailkartukeluarga.index', ['kk' => request('kartukeluarga_id')]);
    }

    public function destroy($id)
    {
        $detailkartukeluarga = $this->detailkartukeluarga->find($id);
        $detailkartukeluarga->delete();

        return redirect()->back()->with('kk', request('kk'));
    }

}

resources/views/detailkartukeluarga/form.blade.php
@extends('_layouts.default')

@section('script-top')
<link rel="stylesheet" href="{{asset('robust/app-assets/css/plugins/forms/validation/form-validation.min.css')}}">
@endsection

@section('script-bottom')
<script src="{{asset('robust/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"> </script>
<script src="{{asset('robust/app-assets/js/scripts/forms/validation/form-validation.min.js')}}"> </script>
<script src="{{asset('js/backend.js')}}"> </script>
@endsection

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            <a href="{{ route('detailkartukeluarga.index', ['kk' => request('kk')]) }}" class="btn btn-secondary float-md-right mt-0">
            	<i class="icon-reply3"></i> Back
            </a>
        </div>
    </div>
</div>
<div class="content-body">
	<section class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<h4 class="card-title" id="basic-layout-square-controls">Form Detail Kartu Keluarga</h4>
					<a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
					<div class="heading-elements">
						<ul class="list-inline mb-0">
							<li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="card-body collapse in">
					<div class="card-block">

						{{-- {!! Form::open(['class' => 'form form-horizontal', 'novalidate']) !!} --}}
						<form action="{{$action}}" method="post" class="form form-hotizontal">
							<input type="hidden" name="_method" value="{{$method}}">
          					{{ csrf_field() }}
							<div class="form-body pt-1">

								<input type="hidden" name="kartukeluarga_id" value="{{request('kk')}}">

								<div class="form-group row position-relative">
									<label for="penduduk_id" class="col-md-2 label-control">NIK Penduduk</label>
									<div class="col-md-10">
										<select class="form-control select2" id="penduduk_id" name="penduduk_id" required>
											<option value="">Pilih NIK Penduduk</option>
											@foreach($penduduk as $index => $item)
												<option value="{{$item->id}}" {{terpilih($item->id, 'penduduk_id')}}>{{$item->nik}} / {{$item->nama}}</option>
											@endforeach
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<div class="form-group row position-relative">
									<label for="role" class="col-md-2 label-control">Status Hubungan Di Dalam Keluarga</label>
									<div class="col-md-10">
										<select class="form-control select2" id="role" name="role" required>
											<option value="">Pilih Status</option>
											<option value="Anak" {{terpilih('Anak', 'role')}}>Anak</option>
											<option value="Ibu" {{terpilih('Ibu', 'role')}}>Ibu</option>
										</select>
										<div class="form-control-position">
			                                <i class="icon-spinner2 spinner" id="spinner-item" style="display: none;"></i>
			                            </div>
										<div class="help-block font-small-3"></div>
									</div>
								</div>

								<hr>

								<div class="offset-md-2">
									<button type="submit" class="btn btn-primary">
										<i class="icon-save"></i> Save
									</button>
								</div>
							</div>
						</form>
						{{-- {!! Form::close() !!} --}}

					</div>
				</div>
			</div>
		</div>
	</section>

</div>
@endsection

resources/views/detailkartukeluarga/index.blade.php
@extends('_layouts.default')

@section('content')
<div class="content-header">
    <div class="row">
        <div class="col-md-6 ">
            {{-- @include('_layout.breadcrumb') --}}
        </div>
        <div class="col-md-6">
            @if(Auth::user()->role == 'pegawai')
                <a href="{{route('detailkartukeluarga.create',['kk' => request('kk')])}}" class="btn btn-primary float-md-right mt-0">
                    <i class="icon-plus3"></i> Tambah
                </a>
            @endif
            <a href="{{url('kartukeluarga')}}" class="btn btn-warning float-md-right mt-0">
                Kembali
            </a>
        </div>
    </div>
</div>
<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">Daftar Detail Kartu Keluarga</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            {{-- <li><a data-action="collapse"><i class="icon-minus4"></i></a></li> --}}
                            {{-- <li><a data-action="expand"><i class="icon-expand2"></i></a></li> --}}
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block pb-0">
                        <form method="get">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Nama Kepala Keluarga : </label>
                                        {{-- <h4>{{$kartukeluarga->nama_penduduk}}</h4> --}}
                                        {{$carikartukeluarga->nama_penduduk}}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group mb-0">
                                        <label class="control-label">Nomor Kartu Keluarga : </label>
                                        {{-- <h4>{{$kartukeluarga->nama_penduduk}}</h4> --}}
                                        {{$carikartukeluarga->nomor}}
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                {{-- <div class="card-body"> --}}
                <div class="card-block">
                    <div class="table-responsive bg-white">
                        <table class="table table-sm mb-0 table-bordered table-hover">
                            <thead class="bg-primary bg-lighten text-white">
                            <!-- <thead class="bg-lighten"> -->
                                <tr>
                                    <th width="20">No.</th>
                                    <th>NIK</th>
                                    <th>Nama</th>
                                    <th>Status Hubungan Dalam Keluarga</th>
                                    @if(Auth::user()->role == 'pegawai')
                                    <th width="180" class="text-xs-center">Actions</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($detailkartukeluarga as $index => $item)
                                    <tr>
                                        <td>{{$index + 1}}</td>
                                        <td>{{$item->nik_penduduk}}</td>
                                        <td>{{$item->nama_penduduk}}</td>
                                        <td>{{$item->role}}</td>
                                        @if(Auth::user()->role == 'pegawai')
                                        <td class="text-xs-center">
                                            <a href="{{route('detailkartukeluarga.edit',[$item->id, 'kk' => request('kk')])}}" class="btn btn-sm btn-green">
                                                <i class="icon-pencil3"></i> Edit
                                            </a>
                                            <a href="{{ route('detailkartukeluarga.destroy',[$item->id, 'kk' => request('kk')])}}"
                                                data-method="delete" data-confirm="Anda yakin akan menghapus data ini ?"
                                                class="btn btn-sm btn-danger" title="Hapus Data">
                                                <i class="icon-trash3"></i>
                                                Delete
                                            </a>
                                        </td>
                                        @endif
                                    </tr>
                                @empty
                                     <tr class="bg-info bg-lighten-4">
                                        <td colspan="5">
                                            <strong class="text-info"><center>Data Kosong</center></strong>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- </div> -->
            </div>

            <div class="card-block pr-0">
                <nav aria-label="Page navigation" class="text-xs-right">
                    {!! $detailkartukeluarga->links() !!}
                </nav>
            </div>
        </div>
    </div>
</div>
@endsection